### ISSUE TITLE
Release empty Rack 2 compatible version.

### ISSUE THREAD

**Issue by lsylvester** [rack/rack-session#15]
As per the suggestion at https://github.com/rack/rack/pull/1805#issuecomment-1047555506 - it would be good to have a version of rack-session that is compatible with rack 2.0.

In particular - I am looking at how [Sidekiq](https://github.com/mperham/sidekiq) can relax its dependency on rack to allow for upgrading to rack 3. While rack-session is only compatible with rack >= 3.0 - we are not able to add rack-session as a dependency so that it can be included in all of the applications.

By providing an empty rack-session gem that is compatible with rack 2 - we allow gems to specify a dependency on rack-session and maintain compatibility with rack 2 and 3 transparently to the application developers. 

I have prepared a branch that I think should be able to be used to build and publish a v0.1.1 version of the gem at https://github.com/rack/rack-session/compare/main...lsylvester:rack-session:v0.1.1 (I have not made this as a PR as it should not be merged).

**Comment by dentarg** [comment]
@ioquatix this sounds like a good idea (I know we touched on it over at [sinatra/sinatra](https://github.com/sinatra/sinatra)) although I don't have a particular use-case for it right now (haven't found the opportunity to dive into trying to make Sinatra work with Rack 3)

**Comment by ioquatix** [comment]
Okay, v1 release of `rack-session` will be for rack < 3, and v2 release will be for rack 3+.

**Comment by ioquatix** [comment]
Okay this is all released. v1.0.0 is Rack < 3 and v2.0.0 is Rack >= 3.

**Comment by ioquatix** [comment]
The same is now also true for the `rackup` gem.
