### ISSUE TITLE
Add GitHub releases for 0.2.1, 0.3.0

### ISSUE THREAD

**Issue by dentarg** [rack/rack-session#17]
The [published versions](https://rubygems.org/gems/rack-session) 0.2.1, 0.3.0 are missing from https://github.com/rack/rack-session/releases (but there are tags https://github.com/rack/rack-session/tags) 

Seeing there's no changelog file in the repo I think it would be good to create the releases to documented what changed in each version.

**Comment by ioquatix** [comment]
All the tags now have releases. I wonder if we can automate this?

**Comment by dentarg** [comment]
Yes possible to automate with Actions and GitHub CLI for example, here's an example workflow: https://github.com/cloudamqp/lavinmq/blob/2286eb041ff9c7b07f71f6a38d5b3f9fe4facf96/.github/workflows/release.yml

**Comment by ioquatix** [comment]
That's super awesome, I'm going to try it out later.
