### ISSUE TITLE
No way to get same_site out

### ISSUE THREAD

**Issue by jamesarosen** [rack/rack-session#2]
`Rack::Session::Abstract::Persisted` [deletes](https://github.com/rack/rack-session/blob/2c4cd627ba1ff5ee2c4a97bca2102ac7ec81729d/lib/rack/session/abstract/id.rb#L258) the `:same_site` option and saves it off as an instance variable, then [applies it](https://github.com/rack/rack-session/blob/2c4cd627ba1ff5ee2c4a97bca2102ac7ec81729d/lib/rack/session/abstract/id.rb#L401-L405) with optional `call` support.

If I have an instance of `Rack::Session::Abstract::Persisted`, I can't get the `same_site` value out of it.

My use-case: I'm migrating from one type of session cookie to another and I want to copy all the directives, but `same_site` is always `nil`. I'm left having to do `other.instance_variable_get(:same_site)`, which is an bug waiting to happen.

**Comment by ioquatix** [comment]
Can you propose a fix for this?

**Comment by jeremyevans** [comment]
Seems like a simple fix would be `attr_reader :same_site`.  @jamesarosen would that work for you?

**Comment by jamesarosen** [comment]
I love simple fixes! My only request is that it goes into the public API docs so it doesn't get accidentally removed.
