### ISSUE TITLE
Needs rack-session.rb

### ISSUE THREAD

**Issue by mperham** [rack/rack-session#6]
Bundler will only automatically require `lib/rack-session.rb` based on the gem name. I think you need to add it which requires "rack/session".

```
gem "sidekiq", path: ".."
gem "concurrent-ruby"

# with Rack >= 3.0
gem "rackup"
gem "rack-session"
```

```
% bundle exec rackup simple.ru
bundler: failed to load command: rackup (/Users/mperham/.gem/ruby/3.1.2/bin/rackup)
/Users/mperham/src/sidekiq/bare/simple.ru:18:in `block in <main>': uninitialized constant Rack::Session (NameError)
Did you mean?  Rack::RACK_SESSION
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `eval'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `new_from_string'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:97:in `load_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:67:in `parse_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:260:in `app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:421:in `wrapped_app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:323:in `block in start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:379:in `handle_profiling'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:322:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:179:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/bin/rackup:5:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `load'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `<top (required)>'
```

**Comment by mperham** [comment]
I know that, I'm just following the readme and pointing out issues where it does not work. The README also does not mention the need to `require "rack/session/cookie"`.

**Comment by jeremyevans** [comment]
I submitted a pull request to add `rack-session.rb`.  Note that if you require 'rack/session' (or 'rack-session' with the PR), you should not need to specifically require `rack/session/cookie`, as `Rack::Session::Cookie` should be autoloaded.

**Comment by mperham** [comment]
> I submitted a pull request to add `rack-session.rb`. Note that if you require 'rack/session' (or 'rack-session' with the PR), you should not need to specifically require `rack/session/cookie`, as `Rack::Session::Cookie` should be autoloaded.

That was not my experience, I had to explicitly require it in my `.ru` file. Maybe `eval` does not autoload constants?

**Comment by jeremyevans** [comment]
`eval` does autoload constants.  You should be able to test that this works from a checkout:

```
$ irb -I lib -r rack/session
irb(main):001:0> Rack::Session.autoload?(:Cookie)
=> "rack/session/cookie"
irb(main):002:0> eval 'Rack::Session::Cookie'
=> Rack::Session::Cookie
```

**Comment by mperham** [comment]
It doesn't work for me.

```
% bundle exec rackup simple.ru
bundler: failed to load command: rackup (/Users/mperham/.gem/ruby/3.1.2/bin/rackup)
/Users/mperham/src/sidekiq/bare/simple.ru:18:in `block in <main>': uninitialized constant Rack::Session (NameError)
Did you mean?  Rack::RACK_SESSION
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `eval'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `new_from_string'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:97:in `load_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:67:in `parse_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:260:in `app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:421:in `wrapped_app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:323:in `block in start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:379:in `handle_profiling'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:322:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:179:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/bin/rackup:5:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `load'
```

```
# Easiest way to run Sidekiq::Web.
# Run with "bundle exec rackup simple.ru"

require "sidekiq/web"

# In a multi-process deployment, all Web UI instances should share
# this secret key so they can all decode the encrypted browser cookies
# and provide a working session.
# Rails does this in /config/initializers/secret_token.rb
secret_key = SecureRandom.hex(32)
use Rack::Session::Cookie, secret: secret_key, same_site: true, max_age: 86400
run Sidekiq::Web
```

**Comment by jeremyevans** [comment]
Can you create a self contained example that doesn't use sidekiq or bundle exec and still has this issue?  As I mentioned in https://github.com/rack/rack-session/issues/7#issuecomment-1209562821, I cannot recreate this in a simple.ru that doesn't use either.  That should help determine the root cause.

**Comment by mperham** [comment]
% bundle
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rack 3.0.0.beta1
Using rack-session 0.1.0
Using webrick 1.7.0
Using bundler 2.3.7
Using rackup 0.2.1
Bundle complete! 3 Gemfile dependencies, 5 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
% rackup bare.ru            
/Users/mperham/src/sidekiq/bare/bare.ru:4:in `block in <main>': uninitialized constant Rack::Session (NameError)
Did you mean?  Rack::RACK_SESSION
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `eval'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `new_from_string'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:97:in `load_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:67:in `parse_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:260:in `app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:421:in `wrapped_app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:323:in `block in start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:379:in `handle_profiling'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:322:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:179:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/bin/rackup:5:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `load'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `<main>'
% bundle exec rackup bare.ru
bundler: failed to load command: rackup (/Users/mperham/.gem/ruby/3.1.2/bin/rackup)
/Users/mperham/src/sidekiq/bare/bare.ru:4:in `block in <main>': uninitialized constant Rack::Session (NameError)
Did you mean?  Rack::RACK_SESSION
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `eval'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `new_from_string'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:97:in `load_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:67:in `parse_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:260:in `app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:421:in `wrapped_app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:323:in `block in start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:379:in `handle_profiling'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:322:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:179:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/bin/rackup:5:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `load'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `<top (required)>'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/mperham/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/bundle:25:in `load'
	from /Users/mperham/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
% ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
```

```
% more bare.ru
require "securerandom"

secret_key = SecureRandom.hex(32)
use Rack::Session::Cookie, secret: secret_key, same_site: true, max_age: 86400
run do
  # nothing
end
```

**Comment by jeremyevans** [comment]
You need to add `require 'rack/session'` to `bare.ru`.  Then it should run.  rack-session is no longer part of rack, so rack itself won't autoload it.

**Comment by mperham** [comment]
rack/session does not define Rack::Session. I think that’s the problem.

**Comment by jeremyevans** [comment]
> rack/session does not define Rack::Session. I think that’s the problem.

https://github.com/rack/rack-session/blob/main/lib/rack/session.rb#L2

**Comment by mperham** [comment]
My rack-session gem has this content:

https://github.com/rack/rack-session/blob/2c4cd627ba1ff5ee2c4a97bca2102ac7ec81729d/lib/rack/session.rb

**Comment by jeremyevans** [comment]
You'll need rack-session 0.2.0, released last week.

**Comment by mperham** [comment]
It does not install with rack 3.0.0.beta1. https://github.com/rack/rack-session/blob/58b582f433004677ae6221fe753abdd68576c02e/rack-session.gemspec#L21

**Comment by jeremyevans** [comment]
> It does not install with rack 3.0.0.beta1. Does this need to be "> 2" to work with a beta?

See #9

**Comment by ioquatix** [comment]
I confirmed that this shouldn't need any `rack-session.rb` to work.

```
 "/Users/samuel/Projects/rack/rack-session/lib/rack/session.rb:9:in `<top (required)>'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler/runtime.rb:73:in `require'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler/runtime.rb:73:in `rescue in block in require'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler/runtime.rb:51:in `block in require'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler/runtime.rb:44:in `each'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler/runtime.rb:44:in `require'",
 "/Users/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.8/lib/bundler.rb:176:in `require'",
 "/Users/samuel/Projects/rack/testapp/app.rb:3:in `<top (required)>'",
```

`Bundler.require` will correctly load in `rack/session.rb`.

Confirmed with the following `app.rb`:

```ruby
#!/usr/bin/env ruby

Bundler.require
```

```ruby
# gems.rb
source "https://rubygems.org"

gem "rack", path: "../rack"
gem "rack-session", path: "../rack-session"
```

I modified my local copy of `rack-session` to get a backtrace when `rack/session.rb` was loaded.

It looks like it's working to me?

**Comment by mperham** [comment]
Ok. I guess something is wrong with my local env; it's not working for me using 3.1.2 / 2.3.20.

**Comment by ioquatix** [comment]
I tried this on Linux too, and it worked. Are you calling `Bundler.require`?

```
> bundle exec ./app.rb

From: /home/samuel/Projects/rack/myapp/app.rb @ line 4 :

    1: #!/usr/bin/env ruby
    2: 
    3: Bundler.require
 => 4: binding.irb

irb(main):001:0> Rack::Session::Cookie
=> Rack::Session::Cookie
irb(main):002:0> Bundler::VERSION
=> "2.3.10"
irb(main):003:0> 
```

**Comment by mperham** [comment]
I'm not. My understanding is that Bundler calls `Bundler.require` as part of `bundle exec`?

**Comment by ioquatix** [comment]
No, that's not correct, they deprecated that behaviour IIRC.

**Comment by ioquatix** [comment]
Is it possible you are hitting this issue?
https://stackoverflow.com/questions/34870704/why-does-bundler-require-not-require-dependencies

**Comment by ioquatix** [comment]
```
#!/usr/bin/env ruby                                    
                                                       
# Bundler.require                                      
binding.irb                                            
```

I changed it to this, and you are right, it's really weird behaviour.

**Comment by ioquatix** [comment]
I see, when you load the local gemspec, it loads `rack/session/version.rb` which defines some of the constants:

```
 "/home/samuel/Projects/rack/rack-session/lib/rack/session/version.rb:9:in `<top (required)>'",
 "/home/samuel/Projects/rack/rack-session/rack-session.gemspec:3:in `require_relative'",
 "/home/samuel/Projects/rack/rack-session/rack-session.gemspec:3:in `<main>'",
 "/home/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.10/lib/bundler.rb:665:in `eval'",
 "/home/samuel/.gem/ruby/3.1.2/gems/bundler-2.3.10/lib/bundler.rb:665:in `eval_gemspec'",
```

This looks like a half defined `Rack::Session` but it's not actually pulling in the gem proper. Let me see if adding `rack-session.rb` fixes this.

**Comment by ioquatix** [comment]
Okay, I added `lib/rack-session.rb` with `binding.irb`, but I could not trigger it with the `app.rb`:

```
#!/usr/bin/env ruby                                    
                                                       
# Bundler.require                                      
binding.irb                                            
```

I can only get it to trigger with `Bundler.require`.

Uncommenting `Bundler.require` will load it, or `rack/session.rb`.

```
> bundle exec ./app.rb

From: /home/samuel/Projects/rack/rack-session/lib/rack-session.rb @ line 2 :

    1: 
 => 2: binding.irb
```

**Comment by ioquatix** [comment]
I think the key point here is, `bundle exec` sets up the environment but won't do `Bundler.require`, you need to do that explicitly, and we've shown that it works with either `rack-session.rb` or `rack/session.rb` (exists already).

**Comment by mperham** [comment]
Should rackup run Bundler,require before eval’ing or does every .ru file
need to call Bundler.require at some point?

**Comment by ioquatix** [comment]
I don't have a strong opinion about that. I think it's probably application framework specific. We could ask team Bundler for their advice. cc @indirect

**Comment by mperham** [comment]
It does seem like something that should be well defined for rackup v1.0.

**Comment by ioquatix** [comment]
This was never part of rackup before, but I agree we can discuss it and consider it as a feature.

**Comment by jeremyevans** [comment]
I'm strongly opposed to running `Bundler.require` by default.  However, maybe if `BUNDLE_GEMFILE` is set in the environment (`bundle exec` sets this), then we can run it.
